### ISSUE TITLE
Minor: run_cmake.sh check 

### ISSUE THREAD

**Issue by utke1** [bradbell/cppad_py#1]
```bin/run_cmake.sh``` check works but ```./bin/run_cmake.sh``` produces error as in
```
jutke@vb:/sandbox/jutke/work/Git/cppad_py$ ./bin/run_cmake.sh 
bin/run_cmake.sh: must be executed from its parent directory
```

**Comment by bradbell** [comment]
It requires one to run
     bin/run_cmake.sh
This is not a security risk because it can only match the one file, and not a location in your execution path.

**Comment by utke1** [comment]
issue is obsolete since the file was removed as of 38bcd521110ec39eb9e586dea76b36423a648490
