### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by zhengp0** [bradbell/cppad_py#14]
Hi @bradbell,

I try to follow the instruction at [here](https://urldefense.com/v3/__https://cppad-py.readthedocs.io/en/latest/setup.py.html__;!!K-Hz7m0Vt54!lpJIlVO_sJunGgm_8lglSdwmxZDryecvmceYzeWMhPYd9zW5Qyxz-neiUTbEFOVr74kusfCtZhx9TOE$), and encountered the following issue.

## General info
* macOS, version is `Ventura 13.5.2`
* Python, version is `3.11.4`

## Extra requirements
During the attempt I found out that I need to install extra package. It will probably be good to include those in the instructions.
* `cmake`, installed through `brew`, current version is `3.27.6`
* `swig`, installed through `brew`, current version is `4.1.1`
* `build`, installed through `pip`, current version is `1.0.3`

## Error
During the command `python3 -m build`, follow error is raised
```
ld: unknown options: -rpath=/path/to/prefix/cppad_py/lib 
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel
```
I found the following post that might potentially solve the issue
https://stackoverflow.com/questions/26472590/ld-unknown-option-rpath-libs-linking-error-while-building-openframework
It suggests to replace `=` to `,`.

Please let me know if you need more information.

**Comment by bradbell** [comment]
I made the suggested change; see
https://github.com/bradbell/cppad_py/commit/7e58f23bb883e80fb2c8da951a8281f6a09e91e0
If it works for you, I will add a comment in whats_new for 2023.

I tested it with g++ on my machine and it works. I was unable to test it with clang. I think this is because clang is not yet fully supported by the setuptools; see
https://github.com/pypa/setuptools/issues/2065

I did try the suggested method
``CC="clang" python setup.py build``

This used clang for the C++ compiler but not linker (which did not work).
One good thing about this test was that I found we need to suppress a certain clang warning:
https://github.com/bradbell/cppad_py/commit/4ccb19a533e931f420bd44249f18db48839cd835

**Comment by zhengp0** [comment]
Thanks @bradbell for the fix. At [`7e58f23`](https://github.com/bradbell/cppad_py/commit/7e58f23bb883e80fb2c8da951a8281f6a09e91e0) I can successfully run `python -m build`.

I have to do some modifications for the installation instruction to make the Python package installation work.

### Python virtual environment
In the instruction we use `--user` option for the `pip install` command. Since I create my own Python virtual environment for testing the installation through [venv](https://docs.python.org/3/library/venv.html), I encounter following error.
```
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
This is one related post
https://stackoverflow.com/questions/30604952/pip-default-behavior-conflicts-with-virtualenv
And I after I remove `--user` option this error disappear.

### Need to specify version
In the instruction we use `dist/cppad_py-*.tar.gz`. For my case, I have two files one from the last unsuccessful build one from the good build. If I naively use the command in the instruction, I will encounter the error message
```
ERROR: Cannot install cppad-py 2023.9.21 (from /path/to/cppad_py/dist/cppad_py-2023.9.21.tar.gz) and cppad-py 2023.9.22 (from /path/to/cppad_py/dist/cppad_py-2023.9.22.tar.gz) because these package versions have conflicting dependencies.
```
After I specify the version, this error disappear.

Hope these help. And issue is resolved and alright to close.

**Comment by bradbell** [comment]
1. I added testing of the new install.
2. I removed --user from the instructions.
3. I added documentation for the version number.
see https://cppad-py.readthedocs.io/en/latest/setup.py.html

The current instructions are just a stop gap while I am changing the source code often. Eventually the install will use pypi to distribute the program (not git).

**Comment by zhengp0** [comment]
Great! This looks good, thanks @bradbell!

**Comment by bradbell** [comment]
Were you able to get including cppad_mixed in cppad_py to work ? i.e., setting
```
include_mixed='true'
```
in bin/get_cppad.sh ?

**Comment by zhengp0** [comment]
@bradbell please see #15
