### ISSUE TITLE
Installation on macOS with `include_mixed='true'`

### ISSUE THREAD

**Issue by zhengp0** [bradbell/cppad_py#15]
I try to install `cppad_py` on macOS as suggested. And I encounter the following issue.

## General info

* macOS, version is `Ventura 13.5.2`
* Python, version is `3.11.4`

## Issue
I changed the `include_mixed='true'` in `bin/get_cppad.sh`. And after I ran `bin/get_cppad_mixed.sh`, `brew` start to install a bunch of packages including `suite-sparse`
```
brew install suite-sparse
...
==> Installing suite-sparse
==> Pouring suite-sparse--7.1.0.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/suite-sparse/7.1.0: 143 files, 69.1MB
```

And when I try to run command `python -m build`, the following error is raised.
```
/path/to/prefix/cppad_py/include/cppad/mixed/include_cholmod.hpp:11:11: fatal error: 'cholmod.h' file not found
# include <cholmod.h>
          ^~~~~~~~~~~
```

I think this is a `brew` + `suite-sparse` issue, but the internet doesn't seem to have too much support on this. If you need more info please let me know.

**Comment by bradbell** [comment]
It is unfortunate that brew is not installing suite-sparse in a standard location so that the include file can be found. 
This appears to be a definite decision that has to do with there not being on system wide installer on the mac.
What we need to do is to find where the cholmod.h include file was installed. 

Looking at some discussions there appears to be a defined shell variable called HOMEBREW_PREFIX; e.g.
https://github.com/orgs/Homebrew/discussions/868
If you have this value on your system, please try the command:
```
find -L $HOMEBREW_PREFIX -name 'cholmod.h'
```
and report back what director it is in.

By the way, we need to figure this out to get dismod_at on the MAC using brew (dismod_at also uses cppad_mixed).

**Comment by zhengp0** [comment]
Thanks for finding the discussions @bradbell! It is very useful. When I ran
```
find -L $HOMEBREW_PREFIX -name 'cholmod.h'
```
I get these
```
/opt/homebrew/include/cholmod.h
/opt/homebrew/var/homebrew/linked/suite-sparse/include/cholmod.h
/opt/homebrew/opt/suite-sparse/include/cholmod.h
/opt/homebrew/opt/suitesparse/include/cholmod.h
/opt/homebrew/Cellar/suite-sparse/7.1.0/include/cholmod.h
```
Can we append `/opt/homebrew/include` in the installation script so that it can work? Like what mentioned in the discussions
```
export CPATH="$HOMEBREW_PREFIX/include:$CPATH"
```

**Comment by bradbell** [comment]
In the file
https://github.com/bradbell/cppad_py/blob/master/bin/get_cppad.sh
at line number 64 you will see
``extra_cxx_flags='-Wall -pedantic-errors -Wno-unused-result -std=c++11'``
Please try changing that line to
``extra_cxx_flags='-Wall -pedantic-errors -Wno-unused-result -std=c++11 -I /opt/homebrew/include``

**Comment by zhengp0** [comment]
Hi @bradbell,

After modifying https://github.com/bradbell/cppad_py/blob/master/bin/get_cppad.sh#L64 to
```
extra_cxx_flags='-Wall -pedantic-errors -Wno-unused-result -std=c++11 -I /opt/homebrew/include'
```
`bin/get_cppad_mixed.sh` run through and I was able to install `cppad_py` and run example in https://cppad-py.readthedocs.io/setup.py.html#setup-py-name

Here are some minor suggestions after work this through.

* I think a setting file host all the installation options will be great. It wasn't obvious to me that the `extra_cxx_flags` in `bin/get_cppad.sh` will propagate to `bin/get_cppad_mixed.sh` until I read the code. I know you probably documented this. However I think having installation setting file will make dependencies and options used in the installation much clear and easier to track.
* I think the entry point is `bin/get_cppad.sh`, however when you have the `include_mixed='true'`, it will ask you to run `bin/get_cppad_mixed.sh`. I originally thought the entry point will automatically run the suitable installation script for you based on the options, and I was surprised it didn't do so. You probably have a reason for it and it will be great to know. This might not be relevant since you mention this won't be exposed to the user.
* I originally made a mistake copying the installation error out. It tells me to find info in `example_install.err`, however it wasn't immediately clear to me where to find the error and the log files. I realize that those files are in `external/cppad_mixed.git` folder since that is where the error come from. If we can track the error better that will be great, but I don't think this is very important right now.

Please let me know if you want me to try other things.

**Comment by bradbell** [comment]
1. Did you run the test suggested for the mixed case ?
   https://cppad-py.readthedocs.io/setup.py.html#setup-py-mixed-case-testing
   ```pytest example/python/*/*_xam.py```
2. I am working on moving the install settings to a separate file and simplifying the corresponding code.
3. Remapping the cppad_mixed install logs back to the location expected by cppad_py is also a good idea.

**Comment by bradbell** [comment]
I moved the settings to a different file. Please see the new install instructions on
https://cppad-py.readthedocs.io/install_settings.py.html

I also added a discussion of the example_install files; see
https://cppad-py.readthedocs.io/get_cppad_mixed.sh.html#example-install

**Comment by zhengp0** [comment]
Hi @bradbell,

## Tests
I ran the suggested tests all of them passes and one warning is generated. Here is the warning just in case it is useful

```
=============================== warnings summary ===============================
example/python/numeric/optimize_fun_class.py:42
  /path/to/cppad_py/example/python/numeric/optimize_fun_class.py:42: DeprecationWarning: invalid escape sequence '\;'
    """

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
The warning comes from don't understand docstring latex `\;`, I don't think this is very important.

And I found out that we need to include extra dependencies, including `pytest` and `matplotlib`. If these two are not necessary for the package to function and just for testing, we can make them optional dependencies.
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

## Install settings
Thanks very much for including all the settings in `install_settings.py`! I really think this is a good change.

## Log files
And thanks very much for remapping and documented the log files!

This issue is good to close.

**Comment by bradbell** [comment]
See the heading 10-03 on
https://cppad-py.readthedocs.io/whats_new_2023.html#whats-new-2023-mm-dd-10-03

**Comment by zhengp0** [comment]
Thanks very much @bradbell! I worked through all the commands in https://cppad-py.readthedocs.io/setup.py.html

* installation + tests
* `include_mixed` as `'false'` and `'true'`

with [9d371dc4](https://github.com/bradbell/cppad_py/tree/9d371dc46bb7acd6c9a60739fa920022663ffccc).

I only need to an extra modification with
```
extra_cxx_flags = '-Wall -pedantic-errors -Wno-unused-result -std=c++11 -I /opt/homebrew/include'
```
in the `bin/install_settings.py` file.

And everything works as expected on my machine. No warnings or errors are generated, and I am able to run through all the tests.

If we can put a note in the documentation for macOS user with brew for `extra_cxx_flags`, that will be great!

**Comment by bradbell** [comment]
I have started the setup.py.error documentation page see the heading Errors on
https://cppad-py.readthedocs.io/setup.py.html#errors

This should make it easy to add more exceptional cases while still keeping the install instructions simple.

**Comment by zhengp0** [comment]
Great, thanks @bradbell! Close this issue now.
