### ISSUE TITLE
problem in cmake called via setup.py with python libs/includes in non-standard locations

### ISSUE THREAD

**Issue by utke1** [bradbell/cppad_py#4]
Moving the install to a server where the python variants are controlled with shell (environment) modules I seem to be unable to resolve cmake's issues with finding libs and header files. 
For example,  shell modules adjusts the path to have 
```
/scratch_n1/jutke/work/Git/cppad_py> which python
/SW/Installs/Anaconda-4.2.0/bin/python
```
and without changing anything else I would get ```Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)```
so if I change e.g. 
```
diff --git a/setup.py b/setup.py
index 1f03307..86d575e 100644
--- a/setup.py
+++ b/setup.py
@@ -54,6 +54,8 @@ command = [
        '-D', 'cppad_cxx_flags='        + quote_str(cppad_cxx_flags),
        '-D', 'python_major_version='   + quote_str( str(python_major_version) ),
        '-D', 'swig_cxx_flags='         + quote_str(swig_cxx_flags),
+       '-D', 'PYTHON_INCLUDE_DIR='     + "/SW/Installs/Anaconda-4.2.0/include",
+       '-D', 'PYTHON_LIBRARY='         + "/SW/Installs/Anaconda-4.2.0/lib",
        '..'
 ]
```
and I did verify that the paths are correct etc. so first I get a confirmation but then later I still get an error
```
-- Found PythonInterp: /SW/Installs/Anaconda-4.2.0/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Found PythonLibs: /SW/Installs/Anaconda-4.2.0/lib (Required is at least version "2") 
...
-- make auto_lib_python: available
FATAL_ERROR,cmake cannot find Python or its libraries
FATAL_ERROR,cmake Python library  not same as interpertor 2.7.12
```
I am guessing this has  something to do with the scripted invocation of cmake which may end up messing with the environment.  
There is also this post https://stackoverflow.com/questions/24174394/cmake-is-not-able-to-find-python-libraries  but the nicer solution that  sets LIB and INCLUDE by inquiring through the interpreter of choice
```
-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
-DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
``` 
needs some extra tweaking - if it is to work through the cmake command generation done in the setup.py. 

Note - I had to edit/shorten the paths a little and mis-copied and pasted but the effect is there.

**Comment by utke1** [comment]
Also, I am getting warnings from cmake like this: 
```
CMake Warning (dev) at /SW/Installs/cmake-3.1.2/share/cmake-3.1/Modules/UseSWIG.cmake:79 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "PERL" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
 /SW/Installs/cmake-3.1.2/share/cmake-3.1/Modules/UseSWIG.cmake:219 (SWIG_MODULE_INITIALIZE)
  CMakeLists.txt:51 (SWIG_ADD_MODULE)
  swig_xam/perl/CMakeLists.txt:31 (add_swig_library)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by utke1** [comment]
I spent some more time trying to dig through the sequence of the ```CMakeLists.txt``` to figure out why this happens but I have never spend enough time with cmake to have a hunch on where to start.  
The best I can offer is some hints from the output for cmake when run with ```--trace``` as follows first in the portion during the execution of cmake where stuff does get found: 
```
==> found.trace.section <==
/apps/scratch_n1/jutke/work/Git/cppad_py/swig_xam/python/CMakeLists.txt(9):  FIND_PACKAGE(PythonInterp ${python_major_version} )
/SW/Installs/cmake-3.1.2/share/cmake-3.1/Modules/FindPythonInterp.cmake(50):  unset(_Python_NAMES )
/SW/Installs/cmake-3.1.2/share/cmake-3.1/Modules/FindPythonInterp.cmake(52):  set(_PYTHON1_VERSIONS 1.6 1.5 )
...
/SW/Installs/cmake-3.1.2/share/cmake-3.1/Modules/FindPackageMessage.cmake(49):  message(STATUS ${msg} )
< -- Found PythonInterp: /SW/Installs/Anaconda-4.2.0/bin/python2 (found suitable version "2.7.12", minimum required is "2") 

```
and now the later section from the same trace relating to the call where it is not found: 
```
==> notfound.trace.section <==
/apps/scratch_n1/jutke/work/Git/cppad_py/lib/example/python/CMakeLists.txt(29):  FIND_PACKAGE(PythonInterp ${python_major_version} )
/SW/Installs/cmake-3.1.2/share/cmake-3.1/Modules/FindPythonInterp.cmake(50):  unset(_Python_NAMES )
/SW/Installs/cmake-3.1.2/share/cmake-3.1/Modules/FindPythonInterp.cmake(52):  set(_PYTHON1_VERSIONS 1.6 1.5 )
...
```
and there is obviously no success message and it just returns to the subsequent check in ```/apps/scratch_n1/jutke/work/Git/cppad_py/lib/example/python/CMakeLists.txt``` and prints that error message but there are no other differences in the two sections of the trace. 
@bradbell  - please let me know if there is anything else I can supply here.

**Comment by bradbell** [comment]
Would it be possible for me to get a  temporary log in on the system in
question ? That might make it easier.

If they are worried about priority information, perhaps you can create a
virtual machine that I can log into that has the same environment.

**Comment by utke1** [comment]
I can't give you access but I was trying to build a docker image that would reproduce the error but wasn't able to. 
As I was doing this I realized that the cmake version in the docker image is newer than the v 3.1.2 I was using. So I installed a new cmake (v 3.12.0) on the server and now get past the python detection issue but have a new problem described in #5
